### List All Users
GET http://localhost:8081/api/v1/users
Authorization: Bearer {{access_token}}

### Get a specific user
GET http://localhost:8081/api/v1/users/user-uuid-here
Authorization: Bearer {{access_token}}

### Update user information
PUT http://localhost:8081/api/v1/users/user-uuid-here
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "first_name": "John",
    "last_name": "Doe"
}

### Delete user
DELETE http://localhost:8081/api/v1/users/user-uuid-here
Authorization: Bearer {{access_token}} 